# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: career_assistant.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'career_assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63\x61reer_assistant.proto\x12\x10\x63\x61reer_assistant\x1a\x1bgoogle/protobuf/empty.proto\"M\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12.\n\x07history\x18\x02 \x03(\x0b\x32\x1d.career_assistant.ChatMessage\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"!\n\rQueryResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"B\n\x12\x43ontactFormRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"7\n\x13\x43ontactFormResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\">\n\x0eMeetingRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"G\n\x0fMeetingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nevent_link\x18\x03 \x01(\t\"\"\n\x0fProfileResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"H\n\x11\x41nalyticsResponse\x12\x33\n\x0cinteractions\x18\x01 \x03(\x0b\x32\x1d.career_assistant.Interaction\"M\n\x0bInteraction\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x10\n\x08response\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t2\xc5\x03\n\x0f\x43\x61reerAssistant\x12Q\n\x0cProcessQuery\x12\x1e.career_assistant.QueryRequest\x1a\x1f.career_assistant.QueryResponse\"\x00\x12\x62\n\x11SubmitContactForm\x12$.career_assistant.ContactFormRequest\x1a%.career_assistant.ContactFormResponse\"\x00\x12X\n\x0fScheduleMeeting\x12 .career_assistant.MeetingRequest\x1a!.career_assistant.MeetingResponse\"\x00\x12Q\n\x10GetAnalyticsData\x12\x16.google.protobuf.Empty\x1a#.career_assistant.AnalyticsResponse\"\x00\x12N\n\x0fGenerateProfile\x12\x16.google.protobuf.Empty\x1a!.career_assistant.ProfileResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'career_assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=73
  _globals['_QUERYREQUEST']._serialized_end=150
  _globals['_CHATMESSAGE']._serialized_start=152
  _globals['_CHATMESSAGE']._serialized_end=196
  _globals['_QUERYRESPONSE']._serialized_start=198
  _globals['_QUERYRESPONSE']._serialized_end=231
  _globals['_CONTACTFORMREQUEST']._serialized_start=233
  _globals['_CONTACTFORMREQUEST']._serialized_end=299
  _globals['_CONTACTFORMRESPONSE']._serialized_start=301
  _globals['_CONTACTFORMRESPONSE']._serialized_end=356
  _globals['_MEETINGREQUEST']._serialized_start=358
  _globals['_MEETINGREQUEST']._serialized_end=420
  _globals['_MEETINGRESPONSE']._serialized_start=422
  _globals['_MEETINGRESPONSE']._serialized_end=493
  _globals['_PROFILERESPONSE']._serialized_start=495
  _globals['_PROFILERESPONSE']._serialized_end=529
  _globals['_ANALYTICSRESPONSE']._serialized_start=531
  _globals['_ANALYTICSRESPONSE']._serialized_end=603
  _globals['_INTERACTION']._serialized_start=605
  _globals['_INTERACTION']._serialized_end=682
  _globals['_CAREERASSISTANT']._serialized_start=685
  _globals['_CAREERASSISTANT']._serialized_end=1138
# @@protoc_insertion_point(module_scope)
