# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import career_assistant_pb2 as career__assistant__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in career_assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CareerAssistantStub(object):
    """The service definition for the Career Assistant AI.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessQuery = channel.unary_unary(
                '/career_assistant.CareerAssistant/ProcessQuery',
                request_serializer=career__assistant__pb2.QueryRequest.SerializeToString,
                response_deserializer=career__assistant__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.SubmitContactForm = channel.unary_unary(
                '/career_assistant.CareerAssistant/SubmitContactForm',
                request_serializer=career__assistant__pb2.ContactFormRequest.SerializeToString,
                response_deserializer=career__assistant__pb2.ContactFormResponse.FromString,
                _registered_method=True)
        self.ScheduleMeeting = channel.unary_unary(
                '/career_assistant.CareerAssistant/ScheduleMeeting',
                request_serializer=career__assistant__pb2.MeetingRequest.SerializeToString,
                response_deserializer=career__assistant__pb2.MeetingResponse.FromString,
                _registered_method=True)
        self.GetAnalyticsData = channel.unary_unary(
                '/career_assistant.CareerAssistant/GetAnalyticsData',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=career__assistant__pb2.AnalyticsResponse.FromString,
                _registered_method=True)
        self.GenerateProfile = channel.unary_unary(
                '/career_assistant.CareerAssistant/GenerateProfile',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=career__assistant__pb2.ProfileResponse.FromString,
                _registered_method=True)


class CareerAssistantServicer(object):
    """The service definition for the Career Assistant AI.
    """

    def ProcessQuery(self, request, context):
        """Processes a user's query and returns a generated response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitContactForm(self, request, context):
        """Submits a contact form entry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScheduleMeeting(self, request, context):
        """Schedules a meeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalyticsData(self, request, context):
        """Retrieves analytics data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateProfile(self, request, context):
        """Generates a professional profile summary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CareerAssistantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessQuery,
                    request_deserializer=career__assistant__pb2.QueryRequest.FromString,
                    response_serializer=career__assistant__pb2.QueryResponse.SerializeToString,
            ),
            'SubmitContactForm': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitContactForm,
                    request_deserializer=career__assistant__pb2.ContactFormRequest.FromString,
                    response_serializer=career__assistant__pb2.ContactFormResponse.SerializeToString,
            ),
            'ScheduleMeeting': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleMeeting,
                    request_deserializer=career__assistant__pb2.MeetingRequest.FromString,
                    response_serializer=career__assistant__pb2.MeetingResponse.SerializeToString,
            ),
            'GetAnalyticsData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalyticsData,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=career__assistant__pb2.AnalyticsResponse.SerializeToString,
            ),
            'GenerateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateProfile,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=career__assistant__pb2.ProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'career_assistant.CareerAssistant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('career_assistant.CareerAssistant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CareerAssistant(object):
    """The service definition for the Career Assistant AI.
    """

    @staticmethod
    def ProcessQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career_assistant.CareerAssistant/ProcessQuery',
            career__assistant__pb2.QueryRequest.SerializeToString,
            career__assistant__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitContactForm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career_assistant.CareerAssistant/SubmitContactForm',
            career__assistant__pb2.ContactFormRequest.SerializeToString,
            career__assistant__pb2.ContactFormResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScheduleMeeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career_assistant.CareerAssistant/ScheduleMeeting',
            career__assistant__pb2.MeetingRequest.SerializeToString,
            career__assistant__pb2.MeetingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalyticsData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career_assistant.CareerAssistant/GetAnalyticsData',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            career__assistant__pb2.AnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/career_assistant.CareerAssistant/GenerateProfile',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            career__assistant__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
